version: "3.9"

volumes:
  pg-data:

services:
  postgres:
    container_name: postgres
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    image: app
    restart: always
    environment:
      - DB_SOURCE=postgresql://user:pass@postgres:5432/postgres?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres
