version: "3.9"

volumes:
  pg-data:

services:
  postgres:
    container_name: postgres
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    image: app
    restart: always
    environment:
      - PG_URL
      - SMTP_FROM
      - SMTP_PASSWORD
      - FILE_STORAGE_ACCESS_KEY
      - FILE_STORAGE_SECRET_KEY
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  integration:
    build:
      context: .
      dockerfile: test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app
