version: "3.9"

services:

  peasant_postgres:
    container_name: peasant_postgres
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
