app:
  name: "quizly-backend"
  version: "0.1"

web:
  url: "http://localhost:8000"

http:
  port: "8080"

logger:
  logLevel: "debug"

postgres:
  poolMax: 2

cache:
  expiration: 1m
  db: 1

cookie:
  secure: false
  httpOnly: true

session:
  expiration: 24h
  cookieKey: "id"
  db: 0

accessToken:
  expiration: 1m
  signingKey: "secret"

smtp:
  host: "smtp.gmail.com"
  port: 587

fileStorage:
  endpoint: "s3.storage.selcloud.ru"
  bucket: "quizly"

email:
  templates:
    accountVerification: "./web/account_verification.html"
  subjects:
    accountVerification: "Спасибо что присоединился к нам, %s!"