app:
  name: "quizish-backend"
  version: "1.0"

http:
  port: "8080"

logger:
  log_level: "debug"
  rollbar_env: "quizish"

postgres:
  pool_max: 2

mongodb:
  database: "quizish"

cache:
  ttl: 1m

oauth:
  github_client_id: "4965a8fd3a9df8f0f405"
  github_scope: "read:user,user:email"

  google_client_id: "1096648041095-qpbc63eibpcomdvjvmmugmfcj7o8pqlm.apps.googleusercontent.com"
  google_scope: "https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile"

  discord_client_id: "938061249177075713"
  discord_scope: "email,identity"

cookie:
  secure: false
  httponly: true

session:
  ttl: 60m
  cookie_key: "id"

access_token:
  ttl: 1m
  signing_key: "secret"

smtp:
  host: "smtp.gmail.com"
  port: 587
  from: "followkacsa@gmail.com"

email:
  verification_template: "./templates/verification_email_%s.html"
