app:
  name: "quizly-backend"
  version: "1.0"

http:
  port: "8080"

logger:
  log_level: "debug"
  rollbar_env: "quizly"

postgres:
  pool_max: 2

cache:
  ttl: 1m

cookie:
  secure: false
  httponly: true

session:
  ttl: 60m
  cookie_key: "id"
  db: 0

access_token:
  ttl: 1m
  signing_key: "secret"

smtp:
  host: "smtp.gmail.com"
  port: 587

email:
  verification_template: "./web/verification_email.html"
  verification_subject: "Спасибо что Вы с нами, %s"
  verification_link: "https://%s/verification?code=%s"


