app:
  name: "quizly-backend"
  version: "1.0"

http:
  port: "8080"

logger:
  log_level: "debug"
  rollbar_env: "quizly"

postgres:
  pool_max: 2

cache:
  ttl: 1m

cookie:
  secure: false
  httponly: true

session:
  ttl: 60m
  cookie_key: "id"
  db: 0

access_token:
  ttl: 1m
  signing_key: "secret"

smtp:
  host: "smtp.gmail.com"
  port: 587
  from: "followkacsa@gmail.com"

email:
  verification_template: "./templates/verification_email_%s.html"
