app:
  name: "answersuck-backend"
  version: "0.1.0"

web:
  url: "http://localhost:8000"

http:
  port: "8080"

logger:
  logLevel: "debug"

postgres:
  poolMax: 2

cache:
  expiration: 1h
  db: 0

cookie:
  secure: false
  httpOnly: true

session:
  expiration: 4h
  cookieKey: "id"

accessToken:
  expiration: 1m
  signingKey: "secret"

password:
  resetTokenExpiration: 1m

smtp:
  host: "smtp.yandex.ru"
  port: 465

fileStorage:
  endpoint: "s3.storage.selcloud.ru"
  bucket: "answersuck"
  ssl: true

  # if true FILE_STORAGE_CDN_DOMAIN env must be set, 
  # otherwise using FILE_STORAGE_DOMAIN env for generating uploaded file url
  cdn: false 

email:
  templates:
    accountVerification: "./web/account_verification.html"
    accountPasswordReset: "./web/account_password_reset.html"
  subjects:
    accountVerification: "Подтверждение аккаунта"
    accountPasswordReset: "Сброс пароля"
  formats:
    accountVerification: "%s/verify?code=%s"
    accountPasswordReset: "%s/reset?token=%s"
